# Generated by Django 4.2.14 on 2024-08-25 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Unknown', max_length=100)),
                ('last_name', models.CharField(default='Unknown', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(default='N/A', max_length=20)),
                ('address1', models.CharField(default=False, max_length=255)),
                ('address2', models.CharField(blank=True, default=False, max_length=255, null=True)),
                ('city', models.CharField(default=False, max_length=100)),
                ('state', models.CharField(default=False, max_length=100)),
                ('country', models.CharField(default=False, max_length=100)),
                ('postal_code', models.CharField(default='N/A', max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
