# Generated by Django 4.2.14 on 2024-08-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
