# Generated by Django 4.2.14 on 2024-08-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_remove_order_address_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
